<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QQACKJ4" name="CNET_Incident Automation Scenarios" tests="1" failures="1" timestamp="28 Oct 2018 18:26:55 GMT" time="156.961" errors="0">
  <testcase name="feature" time="154.904" classname="runner.RunCukes">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [Closed] but found [Resolved]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Closed] but found [Resolved]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: expected [Closed] but found [Resolved]
	at steps.IncidentManagementSteps.validateStateAfterCloseIncident(IncidentManagementSteps.java:356)
	at âœ½.Then Validate State as "Closed" the incident list(CNET_IncidentAutomation.feature:46)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- CNET_Incident Automation Scenarios -->
